# name: Deploy FastAPI to AWS EC2

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Set up SSH
#         uses: webfactory/ssh-agent@v0.9.0
#         with:
#           ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

#       - name: Deploy to EC2
#         run: |
#           ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
#             cd /home/ubuntu/app
#             git pull origin main
#             docker stop fastapi-app || true
#             docker rm fastapi-app || true
#             docker build -t fastapi-app .
#             docker run -d -p 8000:8000 --name fastapi-app fastapi-app
#             sudo systemctl restart nginx
#           EOF

